config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "pages#show"
  resources :ai_tools
  resources :category_pages, only:  [:show, :index]
  resources :searchbars, only: :index

end

app/models/ai_tool.rb
class AiTool < ApplicationRecord
  belongs_to :category
  belongs_to :price

  validates :name, :description, :link, :category_id, :price_id, presence: true
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :ai_tools
end

app/models/price.rb
class Price < ApplicationRecord
  has_many :ai_tools
end

app/models/scraper.rb
  require 'nokogiri'
  require 'open-uri'
  class Scraper
    def scrape_tools
      url = URI.open('https://buzzmatic.net/700-ai-tools-die-ultimative-liste/')
      doc = Nokogiri::HTML(url)

      #Extracting the rows of the table
      rows = doc.css('tr')[0..1136]

      #Extracting the name,description nd link from the data
      rows.each do |row|
        #Extracting name
        toolNameElement = row.css('td')[0]
        toolName = toolNameElement&.text&.strip

        #Extracting description
        toolDescriptionElement = row.css('td')[3]
        toolDescription = toolDescriptionElement&.text&.strip

        #Extracting link
        toolLinkElement = row.css('a').first
        toolLink = toolLinkElement['href'] if toolLinkElement

        #Extracting categories
        toolCategoryElement = row.css('td')[1]
        toolCategory = toolCategoryElement&.text&.strip

        #Extracting prices
        toolPriceElement = row.css('td')[2]
        toolPrice = toolPriceElement&.text&.strip

        #Finding a record with a given category
        category = Category.find_or_create_by(category: toolCategory)

        #Finding a record with a given price
        price = Price.find_or_create_by(price: toolPrice)

        #Finding the record by its name.
        ai_tool = AiTool.find_by(name: toolName)

        if ai_tool
          #Updating the records if found
          ai_tool.update(
            description: toolDescription,
            link: toolLink,
            category_id: category.id,
            price_id: price.id
          )
        else
          #Creating the records not found
          AiTool.create(
            name: toolName,
            description: toolDescription,
            link: toolLink,
            category_id: category.id,
            price_id: price.id
          )
        end
      end
    end
  end

app/controllers/ai_tools_controller.rb
class AiToolsController < ApplicationController

  # View for all the AI tools
  def index
    @ai_tools = AiTool.paginate(page: params[:page], per_page: 25)
  end

  # View for a specific AI tool
  def show
    @ai_tool = AiTool.find(params[:id])
  end

  # Creating a new AI tool
  def new
    @ai_tool = AiTool.new
    @categories = Category.order(:category).map { |category| [category.category, category.id] }
    @prices = Price.order(:price).map { |price| [price.price, price.id] }
  end

  def create
    @ai_tool = AiTool.new(ai_tool_params)
    @categories = Category.order(:category).map { |category| [category.category, category.id] }
    @prices = Price.order(:price).map { |price| [price.price, price.id] }

    if @ai_tool.save
      redirect_to ai_tool_path(@ai_tool.id), notice: "Successfully Created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @ai_tool = AiTool.find(params[:id])
    @categories = Category.order(:category).map { |category| [category.category, category.id] }
    @prices = Price.order(:price).map { |price| [price.price, price.id] }
  end

  def update
    @ai_tool = AiTool.find(params[:id])
    @categories = Category.order(:category).map { |category| [category.category, category.id] }
    @prices = Price.order(:price).map { |price| [price.price, price.id] }
    if @ai_tool.update(ai_tool_params)
      redirect_to ai_tool_path(@ai_tool.id), notice: "Successfully Updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @ai_tool = AiTool.find(params[:id])
    @ai_tool.destroy
    redirect_to root_path, status: :see_other
  end

  private
  def ai_tool_params
    params.require(:ai_tool).permit(:name, :description, :link, :category_id, :price_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/category_pages_controller.rb
class CategoryPagesController < ApplicationController
  def index
      @categories = Category.where.not(category: nil).select(:id, :category)
  end

  def show
    @category = Category.find(params[:id])
    @ai_tools = AiTool.includes(:category).where(category_id: @category.id).paginate(page: params[:page], per_page: 25)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show

  end
end

app/controllers/searchbars_controller.rb
class SearchbarsController < ApplicationController

  def index
    @search_results = AiTool.where("name LIKE ?", AiTool.sanitize_sql_like(params[:search]) + "%")
    if @search_results.blank?
      flash[:message] = "No results found."
    end
  end

  private
  def searchbar_params
    params.require(:ai_tool).permit(:search)
  end
end

app/helpers/ai_tools_helper.rb
module AiToolsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_pages_helper.rb
module CategoryPagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/searchbars_helper.rb
module SearchbarsHelper
end

app/views/ai_tools/edit.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-green" style="font-family: 'Montserrat', sans-serif; font-weight: 700; font-size: 56px; padding-top: 20px"> Edit the AI Tool </h1>

      <p class="text-black" style="font-family: 'Montserrat', sans-serif; font-weight: 400; font-size: 20px; padding-top: 20px;">
        Update the relevant details to edit the AI tool</p>

      <%= form_with model: @ai_tool, html: { class: 'form' } do |form| %>

        <div class="form-group mb-3">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control', style: 'width : 250px;' %>
        </div>
        <div class="form-group mb-3">
          <%= form.label :description %>
          <%= form.text_field :description, class: 'form-control', style: 'width : 250px;' %>
        </div>
        <div class="form-group mb-3">
          <%= form.label :link %>
          <%= form.text_field :link, class: 'form-control', style: 'width : 250px;' %>
        </div>
        <div class="form-group mb-3">
          <%= form.label :category %>
          <%= form.select :category_id, @categories %>
        </div>
        <div class="form-group mb-3">
          <%= form.label :price %>
          <%= form.select :price_id, @prices %>
        </div>

        <div class="vstack gap-2 col-md-5 mx-auto">
          <%= form.submit "Save Changes", class: 'btn btn-primary' %>
          <%= link_to 'Cancel', ai_tool_path(@ai_tool.id), class: 'btn btn-secondary', style: "margin-bottom: 20px" %>
        </div>

        </form>
      <% end %>
    </div>
  </div>
</div>

app/views/ai_tools/index.html.erb
<% @ai_tools.each_with_index do |ai_tool, index| %>
  <div class="accordion" id="accordionExample<%= index %>" style="margin-top: 20px; margin-right: 25px; width: auto">
    <ul style="font-family: 'Roboto', sans-serif;">
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= index %>" aria-expanded="true" aria-controls="collapse<%= index %>">
            <%= link_to ai_tool.name, ai_tool_path(ai_tool.id), style: "color: #333; text-decoration: none; font-weight: bold;" %>
            <br>
          </button>

        </h2>
        <div id="collapse<%= index %>" class="accordion-collapse collapse" data-bs-parent="#accordionExample<%= index %>">
          <div class="accordion-body">
            <strong style="color: black;">Description:</strong>
            <span style="color: #555;"><%= ai_tool.description %></span><br>

            <strong style="color: black;">Link:</strong>
            <%= link_to ai_tool.link, ai_tool.link, target: "_blank", style: "color: #555;" %><br>

            <strong style="color: black;">Category:</strong>
            <span style="color: #555;"><%= ai_tool.category.category %></span><br>

            <strong style="color: black;">Price:</strong>
            <span style="color: #555;"><%= ai_tool.price.price %></span><br>
          </div>
        </div>
      </div>
    </ul>
  </div>
<% end %>





  <ul class="pagination justify-content-center">
    <%= will_paginate @ai_tools, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </ul>

  <br>
  <div class="col-lg-2 text-center">
    <a class="btn btn-primary" href="<%= root_path %>" role="button" style="margin-bottom: 20px">Go back to Home
      page</a>
  </div>

app/views/ai_tools/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-green" style="font-family: 'Montserrat', sans-serif; font-weight: 700; font-size: 56px; padding-top: 20px">Add a new AI Tool</h1>

      <p class="text-black" style="font-family: 'Montserrat', sans-serif; font-weight: 400; font-size: 20px; padding-top: 20px;">
        Enter the details to add a new AI tool</p>

      <%= form_with model: @ai_tool, html: { class: 'form' } do |form| %>
        <div class="form-group mb-3">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control', style: 'width : 250px;' %>
        </div>

        <div class="form-group mb-3">
          <%= form.label :description %>
          <%= form.text_field :description, class: 'form-control', style: 'width : 250px;' %>
        </div>

        <div class="form-group mb-3">
          <%= form.label :link %>
          <%= form.text_field :link, class: 'form-control', style: 'width : 250px;' %>
        </div>

        <div class="form-group mb-3">
          <%= form.label :category %>
          <%= form.select :category_id, @categories, { include_blank: 'Select Category', selected: '' }, class: 'form-select', style: 'width: 250px;' %>
        </div>

        <div class="form-group mb-3">
          <%= form.label :price %>
          <%= form.select :price_id, @prices, { include_blank: 'Select Price', selected: '' }, class: 'form-select', style: 'width: 400px;' %>
        </div>

        <%= form.submit "Create", class: 'btn btn-primary',style: "margin-bottom: 20px"%>
        <%= link_to 'Cancel', root_path, class: 'btn btn-secondary',style: "margin-bottom: 20px" %>
        </form>
      <% end %>
    </div>
  </div>
</div>

app/views/ai_tools/show.html.erb
<div style="margin: 30px 30px 10px 30px;">
  <h2><%= @ai_tool.name %></h2>
  <p><strong>Description:</strong> <%= @ai_tool.description %></p>
  <p><strong>Link:</strong> <%= link_to @ai_tool.link, @ai_tool.link, target: "_blank" %></p>
  <p><strong>Category:</strong> <%= @ai_tool.category.category %></p>
  <p><strong>Price:</strong> <%= @ai_tool.price.price %></p><br>
</div>

<div class="col-lg-2 text-center">
  <div class="d-flex">
    <a class="btn btn-primary text-nowrap" href="<%= edit_ai_tool_path(@ai_tool.id) %>" role="button" style="margin-left: 20px; margin-bottom: 20px">Edit
      the tool</a>
    <a href="<%= ai_tool_path(@ai_tool.id) %>"
       data-turbo-method="delete"
       data-turbo-confirm="Are you sure?"
       class="btn btn-primary text-nowrap"
       style="margin-left: 20px; margin-bottom: 20px">
      Destroy the tool
    </a>
    <a class="btn btn-primary text-nowrap" href="<%= ai_tools_path %>" role="button" style="margin-left: 20px; margin-bottom: 20px">Back
      to AI Tools</a>
    <a class="btn btn-primary text-nowrap" href="<%= root_path %>" role="button" style="margin-left: 20px; margin-bottom: 20px">Go
      back to Home page</a>
  </div>
</div>

app/views/category_pages/index.html.erb
<h1 class="text-center" style="margin: 30px 0px 0px 20px "> You want to see all the AI tools in a single category ? Then
  just click them!! </h1>
<div class="d-flex flex-wrap justify-content-center" style="list-style-type: none; padding-left: 0;">
  <% @categories.each do |category| %>
    <div class="m-2">
      <%= link_to category.category, category_page_path(category.id), class: "btn btn-light", style: "width: 250px; padding: 10px 20px; margin: 30px 20px 0px 0px; box-shadow: 0px 4px 15px rgba(0, 0, 0, 0.1); transition: transform 0.3s ease;", onmouseover: "this.style.transform='translateY(-5px)';", onmouseout: "this.style.transform='none';" %>
    </div>
  <% end %>
</div>

  <br>
  <div class="col-lg-2 text-center">
    <a class="btn btn-primary" style="margin-bottom: 20px" href="<%= root_path %>" role="button">Go back to Home
      page</a>
  </div>

app/views/category_pages/show.html.erb
<h1 class="text-center" style="margin: 40px 0px 0px 20px ">AI Tools for Category: <%= @category.category %></h1>
<div class="d-flex flex-wrap justify-content-center" style="list-style-type: none; padding-left: 0;">
  <% @ai_tools.each do |ai_tool| %>
    <div class="m-2">
      <%= link_to ai_tool.name, ai_tool_path(ai_tool.id), class: "btn btn-light", style: "width: 250px; padding: 10px 20px; margin: 30px 20px 0px 0px; box-shadow: 0px 4px 15px rgba(0, 0, 0, 0.1); transition: transform 0.3s ease;", onmouseover: "this.style.transform='translateY(-5px)';", onmouseout: "this.style.transform='none';" %>
    </div>
  <% end %>
</div>


<ul class="pagination justify-content-center" style="margin-top: 100px">
  <%= will_paginate @ai_tools, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</ul>

<br>

<div class="col-lg-2 text-center">
  <div class="d-flex justify-content-between">
    <a class="btn btn-primary text-nowrap" href="<%= root_path %>" role="button" style="margin-left: 20px; margin-bottom: 20px">Go
      back to Home page</a>
    <a class="btn btn-primary text-nowrap" href="<%= category_pages_path %>" role="button" style="margin-left: 20px; margin-bottom: 20px">Go
      back to Categories</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AiWiki</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">


</head>

<body style="background: radial-gradient(#a2d2b1, #6bb282); margin: 0; min-height: 100vh;">

<!-- Header-->
<nav class="navbar bg-body-tertiary" style="padding: 20px 0; position: static">
  <div class="container-fluid">
    <%= form_tag(searchbars_path, method: :get, class: "d-flex", role: "search") do %>
      <input id="search-input" class="form-control me-2" type="search" placeholder="Search an AI Tool" aria-label="Search" style="margin-left: 30cm" name="search" value="<%= params[:search] %>">
      <%= submit_tag("Search", class: "btn btn-outline-success") %>
    <% end %>
  </div>
</nav>

<% if (controller_name == 'searchbars' && @search_results.blank?) && flash[:message] %>
  <div class="alert alert-info">
    <%= flash[:message] = "No results found." %>
  </div>
<% end %>

<%= yield %>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>



<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">

  <!-- Section: Social media -->
  <section class="d-flex justify-content-end p-4 border-bottom">
    <!-- Setting social media icons -->
    <div>
      <a href="https://www.facebook.com/" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="https://www.google.com/" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="https://www.linkedin.com" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
    </div>
  </section>

  <!-- Section: Resources  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <div class="row mt-3">
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <h6 class="text-uppercase fw-bold mb-4">
            Resources
          </h6>
          <p>
            <a href="https://openai.com/" class="text-reset">Blog</a>
          </p>
          <p>
            <a href="https://www.expert.ai/glossary-of-ai-terms/" class="text-reset">Glossary</a>
          </p>
          <p>
            <a href="https://openai.com/blog/chatgpt-plugins" class="text-reset">Chat GPT Plugins</a>
          </p>
        </div>

        <!-- Legal details -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <h6 class="text-uppercase fw-bold mb-4">
            Legal
          </h6>
          <p>
            <a href="https://en.wikipedia.org/wiki/Information_privacy" class="text-reset">Data Protection</a>
          </p>
          <p>
            <a href="https://en.wikipedia.org/wiki/Data_security" class="text-reset">Terms and Conditions</a>
          </p>
        </div>

        <!-- Contact details -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p>
            <i class="fas fa-home me-3"></i>
            Universitat Straße 3,<br>
            56070 Koblenz
          </p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            remy.varghese@muellmail.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 49 1234 56789</p>
        </div>
      </div>
    </div>
  </section>

</footer>

</body>
</html>

app/views/pages/show.html.erb
<div class="col-lg-6 mx-auto text-center" style="padding-top: 50px;">
  <h1 class="text-green" style="font-family: 'Montserrat', sans-serif; font-weight: 700; font-size: 56px;">AI TOOLS</h1>
  <p class="text-black" style="font-family: 'Montserrat', sans-serif; font-weight: 500; font-size: 25px; margin-top: 40px; padding-top: 20px;">
    Discover a wide range of AI tools to enhance your projects.</p>
  <%= image_tag("AI-tools.png", size: "640x70", alt: "Image", style: "margin-top: 80px;") %>
</div>

<div style="padding-top: 10%;" class="container mt-4 position-absolute top-50 start-50 translate-middle">
  <div class="row justify-content-center"> <!-- Center-align the row -->
    <div class="col-lg-4 text-center">
      <a href="<%= ai_tools_path %>" class="btn btn-light" style="width: 50%; margin-top: 200px; box-shadow: 0px 4px 15px rgba(0, 0, 0, 0.1); transition: transform 0.3s ease;" onmouseover="this.style.transform='translateY(-5px)'" onmouseout="this.style.transform='none'">All
        AI Tools</a>
    </div>
    <div class="col-lg-4 text-center">
      <a href="<%= new_ai_tool_path %>" class="btn btn-light" style="width: 50%; margin-top: 200px; box-shadow: 0px 4px 15px rgba(0, 0, 0, 0.1); transition: transform 0.3s ease;" onmouseover="this.style.transform='translateY(-5px)'" onmouseout="this.style.transform='none'">Create
        an AI Tool</a>
    </div>
    <div class="col-lg-4 text-center">
      <a href="<%= category_pages_path %>" class="btn btn-light" style="width: 50%; margin-top: 200px; box-shadow: 0px 4px 15px rgba(0, 0, 0, 0.1); transition: transform 0.3s ease;" onmouseover="this.style.transform='translateY(-5px)'" onmouseout="this.style.transform='none'">AI
        Tools per Category</a>
    </div>
  </div>
</div>


<div class="col-lg-8 mx-auto text-center" style="padding-top: 85px;">
  <p class="text-black" style="font-family: 'Montserrat', sans-serif; font-weight: 400; font-size: 20px;margin-top: 250px;">
    Numerous new AI tools and programmes have been developed to assist businesses and organisations with automating
    operations,
    analysing data, forecasting trends, and many other tasks. We have outlined the most significant AI technologies in
    this list,
    along with their purposes and potential applications. We've collected more than 1,000 tools and sorted them into
    various categories
    to provide you an overview of the most recent technological advancements on the market, ranging from machine
    learning platforms to tools for natural language processing.
  </p>
</div>
</div>

app/views/searchbars/index.html.erb
<ul style="font-family: 'Roboto', sans-serif;">
  <% @search_results.each do |search_results| %>
    <ul style="margin: 20px 20px 20px 0;; padding: 10px; border-radius: 5px; background-color: #f4f4f4;">

      <strong style="color: #007BFF;">Name:</strong>
      <%= link_to search_results.name, ai_tool_path(search_results.id), style: "color: #333; text-decoration: none; font-weight: bold;" %><br>

      <strong style="color: #007BFF;">Description:</strong>
      <span style="color: #555;"><%= search_results.description %></span><br>

      <strong style="color: #007BFF;">Link:</strong>
      <%= link_to search_results.link, search_results.link, target: "_blank", style: "color: #555;" %><br>

      <strong style="color: #007BFF;">Category:</strong>
      <span style="color: #555;"><%= search_results.category.category %></span><br>

      <strong style="color: #007BFF;">Price:</strong>
      <span style="color: #555;"><%= search_results.price.price %></span><br>
    </ul>
  <% end %>
</ul>

<a class="btn btn-primary text-nowrap" href="<%= root_path %>" role="button" style="margin-left: 20px; margin-bottom: 20px">Go
  back to Home page</a>